POST http://localhost:3333/bingos
Content-Type: application/json

{
  "name": "Bingo teste",
  "date": "2025-05-21T19:00:00.000Z"
}

###

PUT http://localhost:3333/bingos/e332b62c6157
Content-Type: application/json

{
  "name": "Bingo atualizado",
  "date": "2025-05-07T19:00:00.000Z"
}