# Variables
@baseUrl = http://localhost:3333
@bingoId = {{createBingo.response.body.$.bingoId}}

###

# Bingos
# @name createBingo
POST {{baseUrl}}/bingos
Content-Type: application/json

{
  "name": "Bingo Teste",
  "date": "2025-07-25T00:00:00.000Z"
}

###

# @name updateBingo
PUT {{baseUrl}}/bingos/{{bingoId}}
Content-Type: application/json

{
  "name": "Bingo da Terça-Feira",
  "date": "2025-07-15T00:00:00.000Z"
}

###

# @name getBingos
GET {{baseUrl}}/bingos

###

# @name getBingo
GET {{baseUrl}}/bingos/{{bingoId}}

###

# Cards
# @name saveCards
POST {{baseUrl}}/bingos/{{bingoId}}/cards
Content-Type: application/json

{
  "quantity": 500
}

###

# @name getAllCardsNotSaled
GET {{baseUrl}}/bingos/{{bingoId}}/cards

###

# @name sellCards
POST {{baseUrl}}/bingos/{{bingoId}}/cards/sell
Content-Type: application/json

{
  "buyerAddress": "Fake Address",
  "buyerName": "Fake Name",
  "buyerPhone": "Fake Phone",
  "cardsNumbers": [1001, 1002, 1005]
}